name: Deploy

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  deploy_production:
    runs-on: ubuntu-latest
    environment:
      name: production
      url: https://google.com
    steps:
      - run: echo deploy production
